version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:5000/api
      - NODE_ENV=development
    network_mode: "host"
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://localhost:27017/gestionale-docenti
    env_file:
      - ./server/.env
    network_mode: "host"
    volumes:
      - ./server:/app
      - /app/node_modules

volumes:
  node_modules:
