version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:5000
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://host.docker.internal:27017/othocalab
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  node_modules:
