version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=${API_URL:-http://localhost:5000/api}
      - NEXT_PUBLIC_BACKEND_URL=${BACKEND_URL:-http://localhost:5000/api}
      - NODE_ENV=${NODE_ENV:-development}
    ports:
      - "${FRONTEND_HOST:-0.0.0.0}:${FRONTEND_PORT:-3000}:3000"
    restart: always
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=5000
      - MONGODB_URI=${MONGODB_URI:-mongodb://127.0.0.1:27017/gestionale-docenti}
    ports:
      - "${BACKEND_HOST:-0.0.0.0}:${BACKEND_PORT:-5000}:5000"
    restart: always
    volumes:
      - ./server:/app
      - /app/node_modules
